# ------------------------------------------------------------------------------
#  BACKEND
# ------------------------------------------------------------------------------

webburza_wishlist:
    resource: |
        alias: webburza_wishlist.wishlist
        templates: SyliusAdminBundle:Crud
        except: ['show']
        redirect: update
        grid: webburza_wishlist_admin
        section: admin
        vars:
            all:
                header: webburza_wishlist.ui.wishlists
                subheader: webburza_wishlist.ui.manage_wishlists
                templates:
                    form: WebburzaSyliusWishlistBundle:Backend:_form.html.twig
    type: sylius.resource
    prefix: /admin-office
